version: "3.7"

services:

  database:
    container_name: database
    image: mysql:8.0-debian
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=acaldb
      - MYSQL_ROOT_PASSWORD=TrObccrzH11dURytVjTGwOCiK8mba
    ports:
      - "3306:3306"