version: "3.7"

services:

  database:
    container_name: database
    image: mysql:8.0-debian
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
