app:
  version: 0.0.1

spring:

  profile: local
  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/acaldb
    username: root
    password: TrObccrzH11dURytVjTGwOCiK8mba

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      hbm2ddl:  auto
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
        check_nullability: true
  output:
    ansi:
      enabled: always

server:
  port: 8443
  ssl:
    enable: true
    keyStoreType: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: CoXy9QLoJ$M04$3%
    keyAlias: tomcat

security.require-ssl: true
