spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/acaldb
    username: root
    password: TrObccrzH11dUR=/ytVjTGwOCiK8!mba
  jpa:
    hibernate:
      ddl-auto: update
      hbm2ddl:  auto
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: false
        check_nullability: false
  output:
    ansi:
      enabled: always


logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org:
      springframework: info
      hibernate:
        type: info

server:
  port: 8080

app:
  environment:
    dateTimeFormatter: 'dd/mm/yyyy hh:mm:ss'
    dateFormatter:   'dd/mm/yyyy'